title: Ｓｉｄｅｒｅａｌ Ｌｏｂｂｙ
description: 
baseurl: /
url: https://sidereallobby.com
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
include: ['_pages']
